title: SoftUni Finals Project
destination: docs
email: kamenqnakiev@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Personal project of Kamen Yanakiev for SoftUni Advanced CSS Finals.
baseurl: "/SoftUni-CSS-Advanced-Project"
url: "https://github.com/kamenyanakiev/SoftUni-CSS-Advanced-Project" 
github_username:  kamenyanakiev

# Build settings
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
